修sheet到資料庫
[2016-07-14 03:59:00,073: ERROR/MainProcess] Task
臺灣言語平臺.tasks.半瞑自sheets掠轉資料庫[84389c4c-752a-432f-8e94-c7a24d34b374] raised
unexpected: TypeError("半瞑自sheets掠轉資料庫() missing 1 required positional
argument: 'self'",)